Update Index.rst
TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument pull request #218
Opened 2021-03-19 19:19 UTC by marble

Add tip to head over to contribution workflow number 1: The GitHub method

2021-03-19 20:10 UTC, linawolf approved these changes

2021-03-20 08:26 UTC, sypets requested changes

2021-03-20 08:26 UTC, sypets commented on Documentation/GitHub/Index.rst
> +.. tip:: **Looking for help on 'How to edit'?
I get a rendering error, I think the finishing markup for bold (**) is missing. Will push another commit.

2021-03-20 08:29 UTC, sypets approved these changes

2021-03-20 08:29 UTC, merged