[FEATURE] Document diverse ReST content elements
TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument pull request #262
Opened 2021-12-31 12:59 UTC by linawolf

* Cards
* Tabs
* Sidebar
* Confval
* Phpdomain

2022-01-04 15:50 UTC, alexander-nitsche requested changes

2022-01-04 15:50 UTC, alexander-nitsche commented on Documentation/WritingReST/Index.rst
> +   ContentElements/Index
Adding the new content elements as subpages of the new folder "ContentElements" is breaking the current organizing, where each content element is added as subpage to "Reference" and as content element to page "CheatSheet". Will continue with reviewing the single pages as soon as the reorganizing is done.

2022-01-05 13:28 UTC, alexander-nitsche approved these changes
Ready for merging from my side.

2022-01-05 17:25 UTC, tomwarwick approved these changes

2022-01-05 17:55 UTC, merged

2022-05-26 08:24 UTC, sypets commented
@linawolf tip: If using for **Resolves** with a colon to refer to the issue, for example

`Resolves: #255`

as in TYPO3 core - this will close the issue automatically. Here, `solves #255` was used.

(I think you can also use Fixes: but I think it would be easier for everyone if we use the same conventions as in TYPO3 core contribution).

If you do **not** want the issue to close automatically (yet), you can use **Related** instead of Resolves. This is the same in the TYPO3 core. Using this in both core and documentation should hopefully make it easier to manage the issues and get them closed automatically.

This is also described int https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/CommitMessages.html