[TASK] Overhaul Startpage and menu / toctree configuration
TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument pull request #371
Opened 2024-01-24 15:29 UTC by linawolf

2024-01-24 17:59 UTC, brotkrueml requested changes

2024-01-24 17:59 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
>  The documentation index file at :file:`Documentation/Index.rst` is the starting
Maybe better would be: "The documentation start page is the entry point". "Index file" sounds pretty technical.

2024-01-24 17:59 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
>  The startpage should contain an anchor target :rst:`..  _start:` above its
```suggestion
The start page should contain an anchor target :rst:`..  _start:` above its
```

2024-01-24 17:59 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +If your manual has more pages then this one it must contain a table of content
```suggestion
If your manual has more pages then this start page it must contain a table of content
```

More clear.

2024-01-24 17:59 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +The `toctree` on the startpage can be hidden, it then only influences the main
```suggestion
The `toctree` on the start page can be hidden, it then only influences the main
```

2024-01-24 17:59 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +        :caption: BASICS
I would avoid uppercase words. If they should be uppercase by design, that should be done by CSS. If not, it is up to the user and we should not give that example.

2024-01-25 07:06 UTC, linawolf commented on Documentation/GeneralConventions/FileStructure.rst
> +        :caption: BASICS
```suggestion
        :caption: Basics
```

2024-01-25 07:07 UTC, linawolf commented on Documentation/GeneralConventions/FileStructure.rst
>  The documentation index file at :file:`Documentation/Index.rst` is the starting
```suggestion
The documentation start page (:file:`Documentation/Index.rst`) is the entry
```

2024-01-26 09:13 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +        :caption: HOWTOS
```suggestion
        :caption: Howtos
```

2024-01-26 09:14 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +        :caption: ADVANCED
```suggestion
        :caption: Advanced
```

2024-01-26 09:14 UTC, brotkrueml commented on Documentation/GeneralConventions/FileStructure.rst
> +        :caption: MAINTAINERS
```suggestion
        :caption: Maintainers
```

2024-01-26 09:14 UTC, brotkrueml approved these changes

2024-01-26 09:45 UTC, merged